-- Базовая таблица users (создать перед запуском миграций)
-- Выполнить в Supabase SQL Editor

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255),
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  free_balance DECIMAL(20, 8) DEFAULT 0,
  miner_level INTEGER DEFAULT 1,
  miner_power DECIMAL(10, 3) DEFAULT 0.2,
  last_mining TIMESTAMP,
  tasks_completed INTEGER DEFAULT 0,
  referred_by VARCHAR(255),
  banned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by);
