-- Create user_achievements table
CREATE TABLE IF NOT EXISTS user_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id BIGINT NOT NULL,
  achievement_id VARCHAR(100) NOT NULL,
  unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(telegram_id, achievement_id)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_user_achievements_telegram_id ON user_achievements(telegram_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_achievement_id ON user_achievements(achievement_id);

-- Add games_played column to users table if not exists
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS games_played INTEGER DEFAULT 0;

-- Add referral_count column to users table if not exists
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS referral_count INTEGER DEFAULT 0;
